apiVersion: apps/v1
kind: Deployment
metadata:
  name: nop-client-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nop-client-pod
  template:
    metadata:
      labels:
        app: nop-client-pod
    spec:
      containers:
        - name: nop-client-container
          image: <IMAGE>
          env:
            - name: NEXT_PUBLIC_GIS_API
              value: "https://api.nop.kz"
            - name: NEXT_PUBLIC_SPACE_HOST
              valueFrom:
                secretKeyRef:
                  name: nop-secret
                  key: SPACE_HOST
          ports:
            - containerPort: 8080
      dnsPolicy: ClusterFirstWithHostNet

