apiVersion: apps/v1
kind: Deployment
metadata:
  name: nop-admin-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nop-admin-pod
  template:
    metadata:
      labels:
        app: nop-admin-pod
    spec:
      containers:
        - name: nop-admin-container
          image: <IMAGE>
          env:
            - name: VITE_API_URL
              value: "https://api.nop.kz"
            - name: VITE_SPACE_HOST
              valueFrom:
                secretKeyRef:
                  name: nop-secret
                  key: SPACE_HOST
          ports:
            - containerPort: 8080
      imagePullSecrets:
            - name: registry-salam
      dnsPolicy: ClusterFirstWithHostNet

