// code generated by gen.go
// DO NOT EDIT.
package core

const (
	TXT_UNKNOWN_ERROR                       TxtKey = 1
	TXT_INVALID_PRIMARY_CONTACT             TxtKey = 2
	TXT_INVALID_SECONDARY_CONTACT           TxtKey = 3
	TXT_UNAUTHORIZED                        TxtKey = 4
	TXT_EMPTY_PASSWORD                      TxtKey = 5
	TXT_PASSWORD_TOO_SHORT                  TxtKey = 6
	TXT_PASSWORD_TOO_LONG                   TxtKey = 7
	TXT_INVALID_USER_ROLE                   TxtKey = 8
	TXT_INVALID_USER_FIRST_NAME             TxtKey = 9
	TXT_INVALID_USER_LAST_NAME              TxtKey = 10
	TXT_INVALID_USER_LOGIN                  TxtKey = 11
	TXT_USER_NOT_FOUND                      TxtKey = 12
	TXT_USER_ALREADY_EXISTS_WITH_THIS_LOGIN TxtKey = 13
	TXT_USER_AGENT_EMPTY                    TxtKey = 14
	TXT_INVALID_USER_PASSWORD               TxtKey = 15
	TXT_INVALID_PARTNER_NAME                TxtKey = 16
	TXT_INVALID_PARTNER_LINK                TxtKey = 17
	TXT_INVALID_DOCUMENT_FILENAME           TxtKey = 18
	TXT_INVALID_DOCUMENT_TITLE              TxtKey = 19
	TXT_INVALID_NPA_FILENAME                TxtKey = 20
	TXT_INVALID_NPA_TITLE                   TxtKey = 21
	TXT_INVALID_NEWS_TITLE                  TxtKey = 22
	TXT_INVALID_NEWS_CONTENT                TxtKey = 23
	TXT_INVALID_ENTERPRISE_NAME             TxtKey = 24
	TXT_INVALID_ENTERPRISE_LOCATION         TxtKey = 25
	TXT_INVALID_ENTERPRISE_GOV_SHARE        TxtKey = 26
	TXT_INVALID_ENTERPRISE_INDUSTRY         TxtKey = 27
	TXT_INVALID_EVENT_NAME                  TxtKey = 28
	TXT_INVALID_APPLICATION_ENTERPRISE      TxtKey = 29
	TXT_INVALID_APPLICATION_FIO             TxtKey = 30
	TXT_INVALID_APPLICATION_BIN             TxtKey = 31
	TXT_INVALID_APPLICATION_PHONE           TxtKey = 32
	TXT_INVALID_APPLICATION_EMAIL           TxtKey = 33
	TXT_INVALID_APPLICATION_MESSAGE         TxtKey = 34
	TXT_MAX_FILE_SIZE_IS_1MB                TxtKey = 35
	TXT_WRONG_MLSTRING_FORMAT               TxtKey = 36
	TXT_INVALID_EMAIL                       TxtKey = 37
	TXT_UUID_INVALID_LENGTH                 TxtKey = 38
)

var Txts = TxtResource{
	TXT_UNKNOWN_ERROR: MlString{
		KZ: `Белгісіз қате`,
		RU: `Неизвестная ошибка`,
		EN: `Unknown error`,
	},
	TXT_INVALID_PRIMARY_CONTACT: MlString{
		KZ: `Жарамсыз контакт`,
		RU: `Неверный контакт`,
		EN: `Invalid contact`,
	},
	TXT_INVALID_SECONDARY_CONTACT: MlString{
		KZ: `Жарамсыз қосымша контакт`,
		RU: `Неверный дополнительный контакт`,
		EN: `Invalid secondary contact`,
	},
	TXT_UNAUTHORIZED: MlString{
		KZ: `Құқықсыз`,
		RU: `Неавторизованный`,
		EN: `Unauthorized`,
	},
	TXT_EMPTY_PASSWORD: MlString{
		KZ: `Пароль бос`,
		RU: `Пароль пуст`,
		EN: `Password is empty`,
	},
	TXT_PASSWORD_TOO_SHORT: MlString{
		KZ: `Пароль қысқа`,
		RU: `Пароль слишком короткий`,
		EN: `Password is too short`,
	},
	TXT_PASSWORD_TOO_LONG: MlString{
		KZ: `Пароль ұзын`,
		RU: `Пароль слишком длинный`,
		EN: `Password is too long`,
	},
	TXT_INVALID_USER_ROLE: MlString{
		KZ: `Жарамсыз пайдаланушы рөлі`,
		RU: `Неверная роль пользователя`,
		EN: `Invalid user role`,
	},
	TXT_INVALID_USER_FIRST_NAME: MlString{
		KZ: `Жарамсыз пайдаланушы аты`,
		RU: `Неверное имя пользователя`,
		EN: `Invalid user first name`,
	},
	TXT_INVALID_USER_LAST_NAME: MlString{
		KZ: `Жарамсыз пайдаланушы тегі`,
		RU: `Неверная фамилия пользователя`,
		EN: `Invalid user last name`,
	},
	TXT_INVALID_USER_LOGIN: MlString{
		KZ: `Жарамсыз пайдаланушы логині`,
		RU: `Неверный логин пользователя`,
		EN: `Invalid user login`,
	},
	TXT_USER_NOT_FOUND: MlString{
		KZ: `Пайдаланушы табылмады`,
		RU: `Пользователь не найден`,
		EN: `User not found`,
	},
	TXT_USER_ALREADY_EXISTS_WITH_THIS_LOGIN: MlString{
		KZ: `Пайдаланушы бұл логинмен бар`,
		RU: `Пользователь с таким логином уже существует`,
		EN: `User already exists with this login`,
	},
	TXT_USER_AGENT_EMPTY: MlString{
		KZ: `User-Agent бос`,
		RU: `User-Agent пуст`,
		EN: `User-Agent is empty`,
	},
	TXT_INVALID_USER_PASSWORD: MlString{
		KZ: `Жарамсыз пайдаланушы паролі`,
		RU: `Неверный пароль пользователя`,
		EN: `Invalid user password`,
	},
	TXT_INVALID_PARTNER_NAME: MlString{
		KZ: `Жарамсыз партнер аты`,
		RU: `Неверное имя партнера`,
		EN: `Invalid partner name`,
	},
	TXT_INVALID_PARTNER_LINK: MlString{
		KZ: `Жарамсыз партнер сілтемесі`,
		RU: `Неверная ссылка партнера`,
		EN: `Invalid partner link`,
	},
	TXT_INVALID_DOCUMENT_FILENAME: MlString{
		KZ: `Жарамсыз документ файл аты`,
		RU: `Неверное имя файла документа`,
		EN: `Invalid document file name`,
	},
	TXT_INVALID_DOCUMENT_TITLE: MlString{
		KZ: `Жарамсыз документ атауы`,
		RU: `Неверное название документа`,
		EN: `Invalid document title`,
	},
	TXT_INVALID_NPA_FILENAME: MlString{
		KZ: `Жарамсыз НПА файл аты`,
		RU: `Неверное имя файла НПА`,
		EN: `Invalid NPA file name`,
	},
	TXT_INVALID_NPA_TITLE: MlString{
		KZ: `Жарамсыз НПА атауы`,
		RU: `Неверное название НПА`,
		EN: `Invalid NPA title`,
	},
	TXT_INVALID_NEWS_TITLE: MlString{
		KZ: `Жарамсыз жаңалық атауы`,
		RU: `Неверное название новости`,
		EN: `Invalid news title`,
	},
	TXT_INVALID_NEWS_CONTENT: MlString{
		KZ: `Жарамсыз жаңалық мазмұны`,
		RU: `Неверное содержание новости`,
		EN: `Invalid news content`,
	},
	TXT_INVALID_ENTERPRISE_NAME: MlString{
		KZ: `Жарамсыз кәсіпорын атауы`,
		RU: `Неверное название предприятия`,
		EN: `Invalid enterprise name`,
	},
	TXT_INVALID_ENTERPRISE_LOCATION: MlString{
		KZ: `Жарамсыз кәсіпорын орналасуы`,
		RU: `Неверное местоположение предприятия`,
		EN: `Invalid enterprise location`,
	},
	TXT_INVALID_ENTERPRISE_GOV_SHARE: MlString{
		KZ: `Жарамсыз кәсіпорын державалық пайы`,
		RU: `Неверная государственная доля предприятия`,
		EN: `Invalid enterprise government share`,
	},
	TXT_INVALID_ENTERPRISE_INDUSTRY: MlString{
		KZ: `Жарамсыз кәсіпорын саласы`,
		RU: `Неверная отрасль предприятия`,
		EN: `Invalid enterprise industry`,
	},
	TXT_INVALID_EVENT_NAME: MlString{
		KZ: `Жарамсыз іс атауы`,
		RU: `Неверное название события`,
		EN: `Invalid event name`,
	},
	TXT_INVALID_APPLICATION_ENTERPRISE: MlString{
		KZ: `Жарамсыз өтініш кәсіпорын`,
		RU: `Неверное предприятие заявки`,
		EN: `Invalid application enterprise`,
	},
	TXT_INVALID_APPLICATION_FIO: MlString{
		KZ: `Жарамсыз өтініш аты`,
		RU: `Неверное ФИО заявки`,
		EN: `Invalid application FIO`,
	},
	TXT_INVALID_APPLICATION_BIN: MlString{
		KZ: `Жарамсыз өтініш БИН`,
		RU: `Неверный БИН заявки`,
		EN: `Invalid application BIN`,
	},
	TXT_INVALID_APPLICATION_PHONE: MlString{
		KZ: `Жарамсыз өтініш телефон`,
		RU: `Неверный телефон заявки`,
		EN: `Invalid application phone`,
	},
	TXT_INVALID_APPLICATION_EMAIL: MlString{
		KZ: `Жарамсыз өтініш email`,
		RU: `Неверный email заявки`,
		EN: `Invalid application email`,
	},
	TXT_INVALID_APPLICATION_MESSAGE: MlString{
		KZ: `Жарамсыз өтініш хабарлама`,
		RU: `Неверное сообщение заявки`,
		EN: `Invalid application message`,
	},
	TXT_MAX_FILE_SIZE_IS_1MB: MlString{
		KZ: `Файл 1 МБ-дан асады`,
		RU: `Файл не должен превышать 1 МБ`,
		EN: `File should not exceed 1 MB`,
	},
	TXT_WRONG_MLSTRING_FORMAT: MlString{
		KZ: `Жарамсыз MLString пішімі`,
		RU: `Неверный формат MLString`,
		EN: `Invalid MLString format`,
	},
	TXT_INVALID_EMAIL: MlString{
		KZ: `Жарамсыз email`,
		RU: `Неверный email`,
		EN: `Invalid email`,
	},
	TXT_UUID_INVALID_LENGTH: MlString{
		KZ: `UUID ұзындығы жарамсыз`,
		RU: `Неверная длина UUID`,
		EN: `Invalid UUID length`,
	},
}

func GetTxtKeyAsString(k TxtKey) string {
	switch k {
	case TXT_UNKNOWN_ERROR:
		return "unknown_error"
	case TXT_INVALID_PRIMARY_CONTACT:
		return "invalid_primary_contact"
	case TXT_INVALID_SECONDARY_CONTACT:
		return "invalid_secondary_contact"
	case TXT_UNAUTHORIZED:
		return "unauthorized"
	case TXT_EMPTY_PASSWORD:
		return "empty_password"
	case TXT_PASSWORD_TOO_SHORT:
		return "password_too_short"
	case TXT_PASSWORD_TOO_LONG:
		return "password_too_long"
	case TXT_INVALID_USER_ROLE:
		return "invalid_user_role"
	case TXT_INVALID_USER_FIRST_NAME:
		return "invalid_user_first_name"
	case TXT_INVALID_USER_LAST_NAME:
		return "invalid_user_last_name"
	case TXT_INVALID_USER_LOGIN:
		return "invalid_user_login"
	case TXT_USER_NOT_FOUND:
		return "user_not_found"
	case TXT_USER_ALREADY_EXISTS_WITH_THIS_LOGIN:
		return "user_already_exists_with_this_login"
	case TXT_USER_AGENT_EMPTY:
		return "user_agent_empty"
	case TXT_INVALID_USER_PASSWORD:
		return "invalid_user_password"
	case TXT_INVALID_PARTNER_NAME:
		return "invalid_partner_name"
	case TXT_INVALID_PARTNER_LINK:
		return "invalid_partner_link"
	case TXT_INVALID_DOCUMENT_FILENAME:
		return "invalid_document_filename"
	case TXT_INVALID_DOCUMENT_TITLE:
		return "invalid_document_title"
	case TXT_INVALID_NPA_FILENAME:
		return "invalid_npa_filename"
	case TXT_INVALID_NPA_TITLE:
		return "invalid_npa_title"
	case TXT_INVALID_NEWS_TITLE:
		return "invalid_news_title"
	case TXT_INVALID_NEWS_CONTENT:
		return "invalid_news_content"
	case TXT_INVALID_ENTERPRISE_NAME:
		return "invalid_enterprise_name"
	case TXT_INVALID_ENTERPRISE_LOCATION:
		return "invalid_enterprise_location"
	case TXT_INVALID_ENTERPRISE_GOV_SHARE:
		return "invalid_enterprise_gov_share"
	case TXT_INVALID_ENTERPRISE_INDUSTRY:
		return "invalid_enterprise_industry"
	case TXT_INVALID_EVENT_NAME:
		return "invalid_event_name"
	case TXT_INVALID_APPLICATION_ENTERPRISE:
		return "invalid_application_enterprise"
	case TXT_INVALID_APPLICATION_FIO:
		return "invalid_application_fio"
	case TXT_INVALID_APPLICATION_BIN:
		return "invalid_application_bin"
	case TXT_INVALID_APPLICATION_PHONE:
		return "invalid_application_phone"
	case TXT_INVALID_APPLICATION_EMAIL:
		return "invalid_application_email"
	case TXT_INVALID_APPLICATION_MESSAGE:
		return "invalid_application_message"
	case TXT_MAX_FILE_SIZE_IS_1MB:
		return "max_file_size_is_1mb"
	case TXT_WRONG_MLSTRING_FORMAT:
		return "wrong_mlstring_format"
	case TXT_INVALID_EMAIL:
		return "invalid_email"
	case TXT_UUID_INVALID_LENGTH:
		return "uuid_invalid_length"

	default:
		return ""
	}
}
