name: Prod Client

on:
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.REGISTRY }}

  DOCKERFILE_PATH: "client/Dockerfile"
  IMAGE_NAME: "prod-nop-client"

  DEPLOYMENT_FILE_PATH: ".k8s/prod-client.yml"
  DEPLOYMENT_NAME: "prod-nop-client-deployment"

jobs:
  # The "build" workflow
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Log in to private registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login $REGISTRY \
            -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Build container image
        run: |
          docker build \
            -f "$DOCKERFILE_PATH" \
            -t "$REGISTRY/$IMAGE_NAME:${GITHUB_RUN_ID}" .

      - name: Push image to private registry
        run: docker push "$REGISTRY/$IMAGE_NAME:${GITHUB_RUN_ID}"

  # The "deploy" workflow
  deploy:
    runs-on: ubuntu-latest
    needs: build # Run when "build" workflow succeeds
    env:
      KUBECONFIG: ${{ github.workspace }}/kubeconfig
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Write kubeconfig for k3s
        run: echo "${{ secrets.K3S_KUBECONFIG }}" > kubeconfig

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.33.0"

      - name: Update deployment file
        run: TAG=$(echo $GITHUB_RUN_ID) && sed -i 's|<IMAGE>|'$(echo $REGISTRY)'/'$(echo $IMAGE_NAME)':'${TAG}'|' $(echo $DEPLOYMENT_FILE_PATH)

      - name: Deploy to k3s
        run: kubectl apply -f "$DEPLOYMENT_FILE_PATH"

      - name: Verify deployment
        run: kubectl rollout status deployment/"$DEPLOYMENT_NAME"

