name: Prod Client

on:
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.REGISTRY }}

  DOCKERFILE_PATH: "client/Dockerfile"
  IMAGE_NAME: "prod-nop-client"

  DEPLOYMENT_FILE_PATH: ".k8s/prod-client.yml"
  DEPLOYMENT_NAME: "prod-nop-client-deployment"

jobs:
  test-kubectl:
    runs-on: self-hosted
    steps:
      - name: Show runner info
        run: |
          echo "Runner hostname:"
          hostname
          echo "Runner user:"
          whoami

      - name: Test kubectl against k3s
        run: |
          export KUBECONFIG=$HOME/.kube/config
          echo "KUBECONFIG = $KUBECONFIG"
          kubectl get nodes
          kubectl get pods -A || echo "No pods yet, that's fine"

