name: Prod Client

on:
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.REGISTRY }}

  DOCKERFILE_PATH: "client/Dockerfile"
  IMAGE_NAME: "prod-nop-client"

  DEPLOYMENT_FILE_PATH: ".k8s/prod-client.yml"
  DEPLOYMENT_NAME: "prod-nop-client-deployment"
  NAMESPACE: "nop"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Log in to private registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login $REGISTRY \
            -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Build container image
        run: |
          docker build \
          -f "$DOCKERFILE_PATH" \
          -t "$REGISTRY/$IMAGE_NAME:${GITHUB_RUN_ID}" .

      - name: Push image to private registry
        run: docker push "$REGISTRY/$IMAGE_NAME:${GITHUB_RUN_ID}"

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Update deployment file
        run: |
          TAG="${GITHUB_RUN_ID}"
          IMAGE="${REGISTRY}/${IMAGE_NAME}:${TAG}"
          sed -i "s|<IMAGE>|${IMAGE}|" "$DEPLOYMENT_FILE_PATH"

      - name: Deploy to k3s
        run: |
          export KUBECONFIG="$HOME/.kube/config"
          kubectl apply -f "$DEPLOYMENT_FILE_PATH"

      - name: Verify deployment
        run: |
          export KUBECONFIG="$HOME/.kube/config"
          kubectl rollout status deployment/"$DEPLOYMENT_NAME" -n "$NAMESPACE"